### ISSUE TITLE
Remove my name

### ISSUE THREAD

**Issue by GitRowin** [disclearing/Skid-List#1]
Kid called "alexa" on Discord took my messages out of context and made you add me to this list. The fact that you even put it up shows that this whole repo is stupid and only shows 1 side of the story. Feel free to add me on Discord if you want proof:
Rowin#1450

**Comment by freaky767** [comment]
^ rowin isnt a skid

**Comment by disclearing** [comment]
you rat my kids why would i remove a skid l0l fuck off

**Comment by GitRowin** [comment]
I didn't rat him idiot, like I said he took my messages out of context and made it look like I ratted him.
